# Generated by Django 2.2 on 2020-10-15 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_1_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
